[package]
name = "glass-transition"
version = "0.1.0"
edition = "2021"

[features]
default = []
dynamic-linking = ["bevy/dynamic_linking"]

[dependencies]
bevy = "0.12.1"
bevy_rapier3d = { version = "0.23.0", features = ["debug-render-3d"] }

[profile.dev.package."*"]
opt-level = 3
