[package]
name = "glass-transition"
version = "0.1.0"
edition = "2021"

[features]
default = []
dynamic-linking = ["bevy/dynamic_linking"]

[dependencies]
bevy = { version = "0.12.1", features = ["file_watcher"] }
bevy_rapier3d = { version = "0.23.0", features = ["debug-render-3d"] }
random_color = "0.8.0"

[profile.dev.package."*"]
opt-level = 3
